services:
  openai-gateway:
    image: lucienshui/openai-gateway:latest
    container_name: openai-gateway
    volumes:
      - ${PWD}/logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    working_dir: /app
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    restart: always
    entrypoint: ["python3", "main.py"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${PORT:-8000}/api/health || exit 1"]

