[project]
name = "openai-gateway"
version = "0.1.0"
description = "OpenAI Compatible LLM Gateway"
authors = [
    {name = "Lucien",email = "lucien@lucien.ink"}
]
license = {text = "Apache License 2.0"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "uvicorn (>=0.34.2,<0.35.0)",
    "fastapi (>=0.115.12,<0.116.0)",
    "openai (>=1.79.0,<2.0.0)",
    "pydantic (>=2.11.4,<3.0.0)",
    "sse-starlette (>=2.3.5,<3.0.0)"
]

[tool.poetry]
package-mode = false


[tool.poetry.group.test.dependencies]
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
